# generated by Gemini and reviewed by human
# please refer to https://lv2plug.in/ns/lv2core for a whole list of tags

import argparse
import re
import sys
from pathlib import Path

LV2_CATEGORIES = {
    'delay': 'lv2:DelayPlugin',
    'reverb': 'lv2:ReverbPlugin',
    'distortion': 'lv2:DistortionPlugin',
    'waveshaper': 'lv2:WaveshaperPlugin',
    'dynamics': 'lv2:DynamicsPlugin',
    'amplifier': 'lv2:AmplifierPlugin',
    'compressor': 'lv2:CompressorPlugin',
    'envelope': 'lv2:EnvelopePlugin',
    'expander': 'lv2:ExpanderPlugin',
    'gate': 'lv2:GatePlugin',
    'limiter': 'lv2:LimiterPlugin',
    'filter': 'lv2:FilterPlugin',
    'allpass': 'lv2:AllpassPlugin',
    'bandpass': 'lv2:BandpassPlugin',
    'comb': 'lv2:CombPlugin',
    'highpass': 'lv2:HighpassPlugin',
    'lowpass': 'lv2:LowpassPlugin',
    'eq': 'lv2:EQPlugin',
    'multieq': 'lv2:MultiEQPlugin',
    'paraeq': 'lv2:ParaEQPlugin',
    'generator': 'lv2:GeneratorPlugin',
    'constant': 'lv2:ConstantPlugin',
    'instrument': 'lv2:InstrumentPlugin',
    'oscillator': 'lv2:OscillatorPlugin',
    'modulator': 'lv2:ModulatorPlugin',
    'chorus': 'lv2:ChorusPlugin',
    'flanger': 'lv2:FlangerPlugin',
    'phaser': 'lv2:PhaserPlugin',
    'utility': 'lv2:UtilityPlugin',
    'analyser': 'lv2:AnalyserPlugin',
    'converter': 'lv2:ConverterPlugin',
    'function': 'lv2:FunctionPlugin',
    'mixer': 'lv2:MixerPlugin',
    'midi': 'lv2:MIDIPlugin',
    'simulator': 'lv2:SimulatorPlugin',
    'spatial': 'lv2:SpatialPlugin',
    'spectral': 'lv2:SpectralPlugin',
    'pitch': 'lv2:PitchPlugin'
}


def patch_lv2_categories(lv2_dir: str, short_tags: list[str]) -> None:
    lv2_path = Path(lv2_dir)

    if not lv2_path.exists() or not lv2_path.is_dir():
        print(f"Error: Directory '{lv2_dir}' does not exist.")
        sys.exit(1)

    # Validate and convert short tags to proper LV2 URIs
    valid_lv2_tags = []
    for tag in short_tags:
        tag_lower = tag.lower()
        if tag_lower in LV2_CATEGORIES:
            valid_lv2_tags.append(LV2_CATEGORIES[tag_lower])
        else:
            print(f"Error: '{tag}' is not a recognized LV2 category shorthand.")
            print(f"Valid options include: {', '.join(list(LV2_CATEGORIES.keys()))}")
            sys.exit(1)

    # Format the categories into a valid TTL string
    formatted_cats = " , ".join(valid_lv2_tags)

    # Regex to find the generic JUCE plugin declaration
    pattern = re.compile(r'a\s+lv2:Plugin\s*;')
    replacement = f'a lv2:Plugin , {formatted_cats} ;'

    # Process all .ttl files in the directory
    patched_any = False
    for ttl_file in lv2_path.glob('*.ttl'):
        if ttl_file.name == 'manifest.ttl':
            continue

        try:
            content = ttl_file.read_text(encoding='utf-8')
            if pattern.search(content):
                new_content = pattern.sub(replacement, content)
                ttl_file.write_text(new_content, encoding='utf-8')
                print(f"Success: Patched '{ttl_file.name}' with [ {formatted_cats} ]")
                patched_any = True
            else:
                print(f"Skipped: '{ttl_file.name}' (Pattern not found or already patched).")

        except Exception as e:
            print(f"Error processing '{ttl_file.name}': {e}")

    if not patched_any:
        print("Note: No files were patched. Ensure this is a freshly built JUCE LV2 directory.")


if __name__ == "__main__":
    parser = argparse.ArgumentParser(
        description="Inject LV2 category tags into JUCE-generated .ttl files using short names.")
    parser.add_argument("lv2_dir", help="Path to the compiled .lv2 directory")
    parser.add_argument("categories", nargs="+", help="One or more short categories (e.g., compressor dynamics eq)")

    args = parser.parse_args()
    patch_lv2_categories(args.lv2_dir, args.categories)
