# Enable Address Sanitizer
if (DEFINED ENV{ADDRESS_SANITIZER_FLAG})
    set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -fsanitize=address")
    set(CMAKE_C_FLAGS "${CMAKE_C_FLAGS} -fsanitize=address")
    add_compile_options("-fsanitize=address")
    link_libraries("-fsanitize=address")
    message("Enable Address Sanitizer")
endif ()
# Enable Thread Sanitizer
if (DEFINED ENV{THREAD_SANITIZER_FLAG})
    set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -fsanitize=thread")
    set(CMAKE_C_FLAGS "${CMAKE_C_FLAGS} -fsanitize=thread")
    add_compile_options("-fsanitize=thread")
    link_libraries("-fsanitize=thread")
    message("Enable Thread Sanitizer")
endif ()