name: macOS/Windows/Linux Heavy Test

on:
  workflow_dispatch:

# When pushing new commits, cancel any running builds on that branch
concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

env:
  BUILD_TYPE: Release
  BUILD_DIR: Builds
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  DISPLAY: :0 # linux pluginval needs this
  HOMEBREW_NO_INSTALL_CLEANUP: 1
  SCCACHE_GHA_ENABLED: true
  SCCACHE_CACHE_MULTIARCH: 1

jobs:
  build_and_test:
    name: ${{ matrix.name }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: Linux
            os: ubuntu-latest
            pluginval-binary: ./pluginval
            cmake_extra_flags: -DCMAKE_C_COMPILER=clang-21 -DCMAKE_CXX_COMPILER=clang++-21 -DZL_JUCE_FORMATS="VST3" -DZL_HWY_STATIC_TARGET="AVX2"
          - name: macOS
            os: macos-latest
            pluginval-binary: pluginval.app/Contents/MacOS/pluginval
            cmake_extra_flags: -DZL_JUCE_FORMATS="VST3" -DZL_HWY_STATIC_TARGET="NEON"
          - name: Windows
            os: windows-latest
            wix_arch: x64
            vcvars_script: vcvars64.bat
            pluginval-binary: ./pluginval.exe
            cmake_extra_flags: -DCMAKE_C_COMPILER=clang-cl -DCMAKE_CXX_COMPILER=clang-cl -DZL_JUCE_FORMATS="VST3" -DZL_HWY_STATIC_TARGET="AVX2"

    steps:
      - name: Set up Clang (Linux)
        if: runner.os == 'Linux'
        run: |
          wget https://apt.llvm.org/llvm.sh
          chmod +x ./llvm.sh
          sudo ./llvm.sh 21

      - name: Install Deps (Linux)
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update && sudo apt install libasound2-dev libx11-dev libxcomposite-dev libxcursor-dev libxext-dev libxinerama-dev libxrandr-dev libxrender-dev libfreetype-dev libfontconfig1-dev xvfb ninja-build
          sudo /usr/bin/Xvfb $DISPLAY &

      - name: Checkout code
        uses: actions/checkout@v7
        with:
          submodules: recursive
          fetch-depth: 0

      - name: Configure and Build (Linux & macOS)
        if: runner.os != 'Windows'
        shell: bash
        run: |
          cmake -B ${{ env.BUILD_DIR }} -G Ninja -DCMAKE_BUILD_TYPE=${{ env.BUILD_TYPE}} ${{ matrix.cmake_extra_flags }} .
          cmake --build ${{ env.BUILD_DIR }} --config ${{ env.BUILD_TYPE }}

      - name: Configure and Build (Windows)
        if: runner.os == 'Windows'
        shell: cmd
        run: |
          for /f "usebackq tokens=*" %%i in (`"%ProgramFiles(x86)%\Microsoft Visual Studio\Installer\vswhere.exe" -latest -property installationPath`) do set VS_PATH=%%i
          call "%VS_PATH%\VC\Auxiliary\Build\${{ matrix.vcvars_script }}"
          cmake -B ${{ env.BUILD_DIR }} -G Ninja -DCMAKE_BUILD_TYPE=${{ env.BUILD_TYPE}} ${{ matrix.cmake_extra_flags }} .
          cmake --build ${{ env.BUILD_DIR }} --config ${{ env.BUILD_TYPE }}

      - name: Read in .env from CMake # see GitHubENV.cmake
        shell: bash
        run: |
          cat .env # show us the config
          cat .env >> $GITHUB_ENV # pull in our PRODUCT_NAME, etc

      - name: Pluginval setup
        shell: bash
        run: |
          curl -LO "https://github.com/Tracktion/pluginval/releases/download/v1.0.3/pluginval_${{ runner.os }}.zip"
          7z x pluginval_${{ runner.os }}.zip
          echo "PLUGINVAL_DISABLED=Plugin state restoration" >> $GITHUB_ENV

      - name: Setup Pluginval random seed
        id: setup_seed
        shell: bash
        run: |
          CURRENT_DATE_SEED=$(date +%Y%m%d)
          echo "Generated Seed: $CURRENT_DATE_SEED"
          echo "RANDOM_SEED=$CURRENT_DATE_SEED" >> "$GITHUB_OUTPUT"

      - name: Pluginval VST3 validations
        shell: bash
        run: |
          ${{ matrix.pluginval-binary }} --verbose --validate "${{ env.VST3_PATH }}" --disabled-tests "${{ env.PLUGINVAL_DISABLED }}"
        env:
          STRICTNESS_LEVEL: 10
          TIMEOUT_MS: 7200000
          REPEAT: 10
          RANDOM_SEED: "${{ steps.setup_seed.outputs.RANDOM_SEED }}"
